name: 'Performance report comparison'
description: 'Compare the performance metrics between the base branch and the current branch'
inputs:
  current-stats-json-path:
    description: 'The path to the current performance-report.json file'
    required: true
  base-stats-json-path:
    description: 'The path to the base performance-report.json file'
    required: true
  github-token:
    description: 'The Github token'
    required: true
  title:
    description: 'An optional addition to the title, which also helps key comments, useful if running more than 1 copy of this action'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
